class exceptions(Exception):
    def InitializeException(self):
        pass